### ISSUE TITLE
Form style

### ISSUE THREAD

**Issue by brian-c** [zooniverse/Panoptes-Design#4]
I've been waiting for a more interesting form to come up, but there aren't any just yet, so here's the registration form. I'm gonna recommend we leave checkboxes and radio buttons and select elements system-style for now. We can iterate on them later.

This form lives in a dialog, which I don't think needs much in the way of style, but there is a close button that could use some love.

![screen shot 2015-02-09 at 11 10 53 am](https://cloud.githubusercontent.com/assets/464389/6105194/73ca8f54-b04c-11e4-9baf-98fc4f22c029.png)

**Comment by heathv** [comment]
Replaced the reasoning for the real name with a "why?" On hover, it could do some sort of tag or tooltip-style thing with the reason?

Is signing in with facebook/twitter/etc still a thing? Didn't add it, but there's definitely room for them if needed.

![sloan-forms-signinup](https://cloud.githubusercontent.com/assets/4551411/6129516/9c46d3a8-b104-11e4-8eef-c5106ccda73b.png)

**Comment by brian-c** [comment]
Sorry, sorry: there are actually little helper texts that go along with some of the fields.

![screen shot 2015-02-10 at 4 44 19 pm](https://cloud.githubusercontent.com/assets/464389/6131487/3c7e46aa-b144-11e4-9891-37b13b705c5e.png)

Want to incorporate some of those?

Also, mind sticking with the tab style we have? Tabs are going to show up in a couple other places and it'd be nice to keep them consistent for now.

Also, this is the size of my entire screen. Can we tighten it up?

**Comment by heathv** [comment]
Sure, I'll have another go at it.

**Comment by heathv** [comment]
Sorry, realized I never uploaded this :rage1: 

Condensed things up a lot, removed the welcome messaging and add in the helper texts.

![sloan-forms-signinup-alt](https://cloud.githubusercontent.com/assets/4551411/6229914/0b7656d2-b681-11e4-9ca7-c4df5a5d1464.png)
