### ISSUE TITLE
SGL homepage design

### ISSUE THREAD

**Issue by heathv** [zooniverse/Panoptes-Design#7]
Hopefully not too late, but here is a design for the homepage. Nothing too wild, and only real note is the paragraph of text. Not quite long enough to warrant columns so I stuck it into what would be the center column. 

[Here is the Extract link for specs, svg, etc.](http://adobe.ly/1MFKQFG)

![sgl-home](https://cloud.githubusercontent.com/assets/4551411/6672416/6152c09a-cbda-11e4-866a-3d9287ec0f28.jpg)

**Comment by mrniaboc** [comment]
Do you think I should cut that paragraph down to just a sentence or two?
From a design standpoint.

**Comment by brian-c** [comment]
Close enough!
